name: Shell (Micro-Frontend) CI

on:
  push:
    paths:
      - "shell/**"
      - ".github/workflows/shell.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: shell

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile

      - run: bun run lint

      - name: Build
        run: bun run build

      - name: Test
        run: bun test
